
# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://dpg-d73ml55actks7381g5h0-a.singapore-postgres.render.com:5432/studenttap?sslmode=require
spring.datasource.username=studenttap_user
spring.datasource.password=hTudJgeDPoUt1iSnxs2Hs1VXl7KOa9Ou
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ✅ CRITICAL FIX - This solves "no session" error!
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# ===== APP =====
app.base-url=${APP_BASE_URL:https://studenttap-nfc.onrender.com}
app.upload.dir=${UPLOAD_DIR:uploads}

# ===== JWT =====
app.jwt.secret=${JWT_SECRET:StudentTapNFCPortfolioSecretKey2024VeryLongAndSecure123456}
app.jwt.expiration=86400000

# ===== FILE UPLOAD =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# ===== SERVER =====
# ✅ Must use ${PORT} for Render!
server.port=${PORT:8080}


# Cloudinary

#cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dwo42utuh}
#cloudinary.api-key=${CLOUDINARY_API_KEY:594429282963745}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET:fThpO9RF7Kl-KLEsd4mbr7vpHAw}

cloudinary.cloud-name=dwo42utuh
cloudinary.api-key=594429282963745
cloudinary.api-secret=fThpO9RF7Kl-KLEsd4mbr7vpHAw



# ===== DISABLE MAIL =====
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# ===== LOGGING =====
logging.level.com.studenttap=INFO
logging.level.org.springframework.security=WARN


#zgyhjjhydihwuvqc

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codeosoftsolutions@gmail.com
spring.mail.password=zgyhjjhydihwuvqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===== ADMIN SETTINGS =====
# Admin gets alert when company logs in
admin.email=${ADMIN_EMAIL:info@codeosoftsolutions.com}
admin.whatsapp=${ADMIN_WHATSAPP:919247542054}
 




